# Generated by Django 6.0.4 on 2026-06-07 20:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assemblies', '0004_credential'),
        ('organizations', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, help_text='Texto completo da ata gerado automaticamente ou editado manualmente.', verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovada')], default='draft', help_text='Estado atual da ata. Após aprovação, o documento não pode ser alterado.', max_length=20, verbose_name='Status')),
                ('document_url', models.URLField(blank=True, help_text='Link para o arquivo gerado da ata (ex.: PDF armazenado em object storage).', verbose_name='URL do documento')),
                ('generated_at', models.DateTimeField(blank=True, help_text='Data/hora em que a ata foi gerada automaticamente pelo sistema.', null=True, verbose_name='Gerada em')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Data/hora em que a ata foi formalmente aprovada pelos participantes.', null=True, verbose_name='Aprovada em')),
                ('assembly', models.OneToOneField(help_text='Assembleia à qual esta ata pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='assemblies.assembly', verbose_name='Assembleia')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Ata',
                'verbose_name_plural': 'Atas',
                'ordering': ['-generated_at'],
            },
        ),
    ]
