# Generated by Django 6.0.4 on 2026-06-07 20:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0001_initial'),
        ('organizations', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinuteSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, help_text='Cargo ou função do membro no momento da assinatura (ex.: Secretário, Presidente).', max_length=100, verbose_name='Papel/Função')),
                ('signature_token', models.CharField(editable=False, help_text='Token criptográfico único gerado automaticamente ao registrar a assinatura.', max_length=128, unique=True, verbose_name='Token de assinatura')),
                ('signed_at', models.DateTimeField(blank=True, help_text='Data/hora em que a assinatura foi registrada.', null=True, verbose_name='Assinado em')),
                ('member', models.ForeignKey(help_text='Membro que está assinando a ata.', on_delete=django.db.models.deletion.CASCADE, related_name='minute_signatures', to='organizations.member', verbose_name='Membro')),
                ('minutes', models.ForeignKey(help_text='Ata à qual esta assinatura pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='minutes.minutes', verbose_name='Ata')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Assinatura de Ata',
                'verbose_name_plural': 'Assinaturas de Ata',
                'ordering': ['signed_at'],
                'constraints': [models.UniqueConstraint(fields=('minutes', 'member'), name='unique_signature_per_member_per_minutes', violation_error_message='Este membro já assinou esta ata.')],
            },
        ),
    ]
