# Generated by Django 6.0.4 on 2026-05-11 19:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('condominio', 'Condomínio'), ('sindicato', 'Sindicato'), ('associacao', 'Associação')], default='condominio', max_length=20)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('plan', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'ordering': ['name'],
            },
        ),
    ]
