# Generated by Django 6.0.4 on 2026-05-27 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('convoked', 'Convocada'), ('open', 'Em andamento'), ('closed', 'Encerrada'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Status')),
                ('mode', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrido', 'Híbrido')], default='presencial', max_length=20, verbose_name='Modalidade')),
                ('scheduled_at', models.DateTimeField(verbose_name='Data/hora agendada')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de início')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de encerramento')),
                ('quorum_required', models.PositiveSmallIntegerField(default=50, help_text='Percentual mínimo de membros presentes para validar a assembleia.', verbose_name='Quórum necessário (%)')),
                ('location', models.CharField(blank=True, help_text='Endereço físico para assembleias presenciais ou híbridas.', max_length=255, verbose_name='Local')),
                ('meeting_url', models.URLField(blank=True, help_text='Link de acesso para assembleias online ou híbridas.', verbose_name='URL da reunião')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Assembleia',
                'verbose_name_plural': 'Assembleias',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
