# Generated by Django 6.0.4 on 2026-05-27 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0001_initial'),
        ('organizations', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('postal', 'Correio'), ('edital', 'Edital')], default='email', max_length=20, verbose_name='Canal de envio')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Data/hora em que a convocação foi efetivamente enviada.', null=True, verbose_name='Enviado em')),
                ('is_second_call', models.BooleanField(default=False, help_text='Marque se esta é uma segunda chamada da assembleia.', verbose_name='Segunda convocação')),
                ('delivery_status', models.JSONField(blank=True, default=dict, help_text='Payload JSON retornado pelo serviço de envio com detalhes da entrega.', verbose_name='Status de entrega')),
                ('notes', models.TextField(blank=True, help_text='Notas internas sobre esta convocação.', verbose_name='Observações')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='assemblies.assembly', verbose_name='Assembleia')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Convocação',
                'verbose_name_plural': 'Convocações',
                'ordering': ['-sent_at'],
            },
        ),
    ]
