# Generated by Django 6.0.4 on 2026-05-27 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0002_convocation'),
        ('organizations', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_url', models.URLField(blank=True, help_text='Link para o documento digitalizado da procuração (opcional).', verbose_name='URL do documento')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para revogar a procuração sem excluí-la.', verbose_name='Ativa')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxies', to='assemblies.assembly', verbose_name='Assembleia')),
                ('grantor', models.ForeignKey(help_text='Membro que concede a procuração.', on_delete=django.db.models.deletion.CASCADE, related_name='proxies_granted', to='organizations.member', verbose_name='Outorgante')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('proxy_member', models.ForeignKey(help_text='Membro que recebe e exercerá os direitos de voto.', on_delete=django.db.models.deletion.CASCADE, related_name='proxies_received', to='organizations.member', verbose_name='Procurador')),
            ],
            options={
                'verbose_name': 'Procuração',
                'verbose_name_plural': 'Procurações',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('assembly', 'grantor'), name='unique_proxy_grantor_per_assembly', violation_error_message='Este membro já possui uma procuração registrada nesta assembleia.')],
            },
        ),
    ]
