# Generated by Django 6.0.4 on 2026-05-27 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0003_proxy'),
        ('organizations', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('postal', 'Correio'), ('edital', 'Edital')], default='email', help_text='Meio pelo qual o membro realizou o credenciamento.', max_length=20, verbose_name='Canal de check-in')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora do check-in')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP registrado no momento do credenciamento online.', null=True, verbose_name='Endereço IP')),
                ('device_info', models.CharField(blank=True, help_text='User-agent ou descrição do dispositivo usado no check-in online.', max_length=512, verbose_name='Informações do dispositivo')),
                ('access_token', models.CharField(blank=True, help_text='Token único enviado ao membro para autenticação no check-in online.', max_length=128, unique=True, verbose_name='Token de acesso')),
                ('token_used_at', models.DateTimeField(blank=True, help_text='Data/hora em que o token de acesso foi consumido.', null=True, verbose_name='Token utilizado em')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='assemblies.assembly', verbose_name='Assembleia')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='organizations.member', verbose_name='Membro')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Credencial',
                'verbose_name_plural': 'Credenciais',
                'ordering': ['-checked_in_at'],
                'constraints': [models.UniqueConstraint(fields=('assembly', 'member'), name='unique_credential_per_member_per_assembly', violation_error_message='Este membro já possui credencial registrada nesta assembleia.')],
            },
        ),
    ]
