# Generated by Django 6.0.4 on 2026-05-28 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assemblies', '0004_credential'),
        ('organizations', '0002_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Breve descrição do item de pauta a ser votado.', max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Detalhamento do item de pauta, se necessário.', verbose_name='Descrição')),
                ('order_index', models.PositiveSmallIntegerField(help_text='Posição do item na pauta da assembleia (deve ser único por assembleia).', verbose_name='Ordem')),
                ('quorum_type', models.CharField(choices=[('presenca', 'Presentes'), ('total', 'Total de membros')], default='presenca', help_text='"Presentes" usa o total de credenciados; "Total de membros" usa todos os membros ativos da organização.', max_length=10, verbose_name='Tipo de quórum')),
                ('quorum_required', models.PositiveSmallIntegerField(default=50, help_text='Percentual mínimo de votos necessários para aprovação.', verbose_name='Quórum mínimo (%)')),
                ('vote_mode', models.CharField(choices=[('aberto', 'Aberto (nominal)'), ('secreto', 'Secreto (anônimo)')], default='aberto', max_length=10, verbose_name='Modo de votação')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('open', 'Em votação'), ('closed', 'Encerrado')], default='pending', max_length=10, verbose_name='Status')),
                ('opened_at', models.DateTimeField(blank=True, help_text='Data/hora em que a votação deste item foi iniciada.', null=True, verbose_name='Aberto em')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Data/hora em que a votação deste item foi encerrada.', null=True, verbose_name='Encerrado em')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='assemblies.assembly', verbose_name='Assembleia')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Item de pauta',
                'verbose_name_plural': 'Itens de pauta',
                'ordering': ['assembly', 'order_index'],
                'constraints': [models.UniqueConstraint(fields=('assembly', 'order_index'), name='unique_order_index_per_assembly', violation_error_message='Já existe um item com este número de ordem nesta assembleia.')],
            },
        ),
    ]
