# Generated by Django 6.0.4 on 2026-05-28 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0001_agenda_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Nome da opção de voto (ex.: "Sim", "Não", "Abstenção").', max_length=100, verbose_name='Rótulo')),
                ('total_count', models.PositiveIntegerField(default=0, help_text='Contador acumulado de votos para esta opção. Atualizado via increment().', verbose_name='Total de votos')),
                ('agenda_item', models.ForeignKey(help_text='Item de pauta ao qual esta opção de voto pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='vote_options', to='votings.agendaitem', verbose_name='Item de pauta')),
            ],
            options={
                'verbose_name': 'Opção de voto',
                'verbose_name_plural': 'Opções de voto',
                'ordering': ['agenda_item', 'label'],
                'constraints': [models.UniqueConstraint(fields=('agenda_item', 'label'), name='unique_vote_label_per_agenda_item', violation_error_message='Já existe uma opção com este rótulo neste item de pauta.')],
            },
        ),
    ]
