# Generated by Django 6.0.4 on 2026-05-28 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0004_credential'),
        ('organizations', '0002_member'),
        ('votings', '0002_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(help_text='Canal pelo qual o voto foi registrado (presencial, online, etc.).', max_length=20, verbose_name='Canal')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP do dispositivo que registrou o voto.', null=True, verbose_name='Endereço IP')),
                ('voted_at', models.DateTimeField(blank=True, help_text='Data/hora em que o voto foi registrado.', null=True, verbose_name='Votado em')),
                ('member_id_hash', models.CharField(blank=True, help_text='SHA-256 do UUID do membro. Sempre preenchido; é a única identificação em votação secreta.', max_length=64, verbose_name='Hash do membro')),
                ('vote_label_hash', models.CharField(blank=True, help_text='SHA-256 do rótulo da opção escolhida. Preenchido automaticamente no save().', max_length=64, verbose_name='Hash da opção')),
                ('integrity_hash', models.CharField(blank=True, help_text='SHA-256 combinando agenda_item_id + member_id_hash + vote_label_hash + voted_at. Permite verificação forense de adulteração.', max_length=64, verbose_name='Hash de integridade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vote_records', to='votings.agendaitem', verbose_name='Item de pauta')),
                ('member', models.ForeignKey(blank=True, help_text='FK visível apenas em votação aberta. Nulo em votação secreta — identidade preservada apenas via member_id_hash.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vote_records', to='organizations.member', verbose_name='Membro')),
                ('proxy', models.ForeignKey(blank=True, help_text='Preenchido quando o voto foi exercido por procuração.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_records', to='assemblies.proxy', verbose_name='Procuração')),
                ('vote', models.ForeignKey(help_text='Opção de voto selecionada pelo membro.', on_delete=django.db.models.deletion.PROTECT, related_name='records', to='votings.vote', verbose_name='Opção escolhida')),
            ],
            options={
                'verbose_name': 'Registro de voto',
                'verbose_name_plural': 'Registros de voto',
                'ordering': ['agenda_item', 'voted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('agenda_item', 'member'), name='unique_open_vote_per_member_per_item', violation_error_message='Este membro já registrou um voto neste item de pauta (votação aberta).'), models.UniqueConstraint(condition=models.Q(('member__isnull', True)), fields=('agenda_item', 'member_id_hash'), name='unique_secret_vote_per_member_hash_per_item', violation_error_message='Este membro já registrou um voto neste item de pauta (votação secreta).')],
            },
        ),
    ]
